# Setup with network because of two different docker-compose files
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects

version: "3.7"

services:
  react-app:
    image: worktools-frontend
    container_name: worktools-frontend-container
    build:
      context: ..
      dockerfile: ./docker-files/Dockerfile
    volumes:
      - ../frontend/:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    command: >
      sh -c "npm run start"
    networks:
      - docker-files_api-network

networks:
  docker-files_api-network:
    external: true