# https://www.geeksforgeeks.org/how-to-dockerize-a-reactjs-app/
FROM node:alpine AS development

# Set NODE_ENV
ENV NODE_ENV development

# set working directory
WORKDIR /app

## add `/app/node_modules/.bin` to $PATH
#ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
#COPY ./package.json ./
#RUN npm install

# Copy all the files in our project
#COPY . .

#EXPOSE 3000

# start app
#CMD ["npm", "start"]

